### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by Rahe** [BeAPI/composer-make-stable#4]
Hello,

The package bea/composer/make-stable isn't a package vendor/namespace allowed.
Composer throw errors at each composer install/update.
We need to rename it to beapi/composer-make-stable in my opinion.

We have to :

Make a tag if not already wit the old namespace
Change the vendor/package name and make a new tag

Nicolas,

**Comment by asadowski10** [comment]
okey

**Comment by romain-d** [comment]
En fait, il doit pas y avoir de double / ? c'est ça ?

**Comment by Rahe** [comment]
Oui

**Comment by Rahe** [comment]
Done in 2.0.0
